//! # RustlsConnector
//!
//! Production-safe default TLS connector using the `rustls` crate.
//! Supports:
//!
//! * Configurable SNI hostname (set per-connection)
//! * ALPN protocol negotiation (`h2`, `http/1.1`, custom)
//! * Certificate verification toggle (for testing)
//! * Early data (0-RTT) support
//!
//! ## Usage
//!
//! ```rust,ignore
//! let config = TlsConnectorConfig {
//!     alpn: vec!["h2".into(), "http/1.1".into()],
//!     verify_certs: true,
//!     ..Default::default()
//! };
//! let connector = RustlsConnector::new(config)?;
//! let tls_stream = connector.connect("example.com", tcp_stream).await?;
//! ```

use std::pin::Pin;
use std::sync::Arc;

use anyhow::{Context, Result};
use tokio::io::{AsyncRead, AsyncWrite};
use tokio::net::TcpStream;
use tokio_rustls::TlsConnector as TokioTlsConnector;
use tracing::warn;

use rustls::pki_types::ServerName;
use rustls::ClientConfig;

use crate::tls::{BoxedStream, TlsConnector, TlsConnectorConfig};

/// TLS connector backed by the `rustls` library.
///
/// This is the safe default: it uses a well-audited TLS implementation with
/// configurable SNI, ALPN, and cipher suites.  The actual ClientHello bytes
/// on the wire are generated by rustls, not by our `ClientHelloBuilder`.
///
/// To place a custom `ClientHelloBuilder` fingerprint on the wire, use
/// `CustomClientHelloConnector` instead.
#[derive(Clone)]
pub struct RustlsConnector {
    /// The inner tokio-rustls connector.
    inner: TokioTlsConnector,
    /// Our config for reference / logging.
    config: TlsConnectorConfig,
}

impl RustlsConnector {
    /// Create a new `RustlsConnector` from the given config.
    ///
    /// # Errors
    ///
    /// Returns an error if the `rustls::ClientConfig` cannot be built
    /// (e.g. if no root certificates are available and verification is on).
    pub fn new(config: TlsConnectorConfig) -> Result<Self> {
        let client_config = build_client_config(&config)?;
        let inner = TokioTlsConnector::from(Arc::new(client_config));

        Ok(Self { inner, config })
    }

    /// Access the underlying connector config (for inspection).
    pub fn config(&self) -> &TlsConnectorConfig {
        &self.config
    }
}

#[async_trait::async_trait]
impl TlsConnector for RustlsConnector {
    /// Connect to `domain` over TLS using the given TCP stream.
    ///
    /// The domain is used as the SNI hostname.  The returned boxed stream
    /// implements `AsyncRead + AsyncWrite` for use in the relay engine.
    async fn connect(&self, domain: &str, stream: TcpStream) -> Result<BoxedStream> {
        let server_name = ServerName::try_from(domain.to_string())
            .with_context(|| format!("Invalid SNI domain: {domain}"))?;

        let tls_stream = self
            .inner
            .connect(server_name, stream)
            .await
            .with_context(|| format!("TLS handshake failed for {domain}"))?;

        // Log negotiated ALPN protocol
        if let Some(alpn) = tls_stream.get_ref().1.alpn_protocol() {
            let alpn_str = String::from_utf8_lossy(alpn);
            tracing::debug!(%domain, alpn = %alpn_str, "TLS handshake complete");
        } else {
            tracing::debug!(%domain, "TLS handshake complete (no ALPN)");
        }

        Ok(Box::pin(tls_stream))
    }
}

// ---------------------------------------------------------------------------
// Shared helper: build a rustls ClientConfig from TlsConnectorConfig
// ---------------------------------------------------------------------------

/// Build a `rustls::ClientConfig` from our `TlsConnectorConfig`.
///
/// This helper is used by both `RustlsConnector` and `CustomClientHelloConnector`.
pub fn build_client_config(config: &TlsConnectorConfig) -> Result<ClientConfig> {
    // ── Two paths: verified or dangerous ────────────────────────
    let mut builder = if config.verify_certs {
        let mut root_store = rustls::RootCertStore::empty();

        // Use webpki-roots as the default CA store
        root_store.extend(
            webpki_roots::TLS_SERVER_ROOTS
                .iter()
                .cloned(),
        );
        tracing::debug!("Using webpki-roots certificate store");

        ClientConfig::builder()
            .with_root_certificates(root_store)
            .with_no_client_auth()
    } else {
        warn!("TLS certificate verification is DISABLED — do not use in production");
        let verifier = Arc::new(crate::tls::PermissiveVerifier);
        ClientConfig::builder()
            .dangerous()
            .with_custom_certificate_verifier(verifier)
            .with_no_client_auth()
    };

    // Configure ALPN protocols
    let alpn_protos: Vec<Vec<u8>> = config
        .alpn
        .iter()
        .map(|p| p.as_bytes().to_vec())
        .collect();
    if !alpn_protos.is_empty() {
        builder.alpn_protocols = alpn_protos;
    }

    // Enable early data if configured
    if config.enable_early_data {
        builder.enable_early_data = true;
    }

    Ok(builder)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rustls_connector_creation() {
        let config = TlsConnectorConfig {
            alpn: vec!["http/1.1".into()],
            verify_certs: false, // disable for test
            ..Default::default()
        };
        let connector = RustlsConnector::new(config).unwrap();
        assert_eq!(connector.config().alpn[0], "http/1.1");
    }

    #[test]
    fn test_rustls_connector_with_custom_alpn() {
        let config = TlsConnectorConfig {
            alpn: vec!["h2".into(), "http/1.1".into()],
            verify_certs: false,
            ..Default::default()
        };
        let connector = RustlsConnector::new(config).unwrap();
        assert_eq!(connector.config().alpn.len(), 2);
    }

    #[test]
    fn test_rustls_connector_with_verify_disabled() {
        let config = TlsConnectorConfig {
            verify_certs: false,
            ..Default::default()
        };
        // Should succeed even with no root certs
        let connector = RustlsConnector::new(config).unwrap();
        assert!(!connector.config().verify_certs);
    }

    #[test]
    fn test_server_name_parsing() {
        // Verify that valid domain names parse correctly
        let valid_names = ["example.com", "www.cloudflare.com", "auth.vercel.com", "xn--fsqu00a.xn--0zwm56d"];
        for name in &valid_names {
            let sn = ServerName::try_from(*name);
            assert!(sn.is_ok(), "Failed to parse valid domain: {name}");
        }
    }
}
