//! # CustomClientHelloConnector
//!
//! Sends a custom TLS ClientHello (generated by our `ClientHelloBuilder`)
//! on the wire, then completes the handshake using a `tokio-rustls`
//! connector wrapping a `TlsBufferIo` adapter.
//!
//! ## How It Works
//!
//! 1. Generate a custom ClientHello with the desired JA3 fingerprint using
//!    `ClientHelloBuilder::generate()`.
//! 2. Create a `TlsBufferIo<TcpStream>` that replaces rustls's first write
//!    (its own ClientHello) with our custom one.
//! 3. Connect using `tokio_rustls::TlsConnector` on the buffered stream.
//! 4. From the server's perspective, it receives our custom ClientHello.
//! 5. From rustls's perspective, it produced a ClientHello (which was
//!    silently replaced) and the server responded correctly.

use std::pin::Pin;
use std::sync::Arc;

use anyhow::{Context, Result};
use bytes::Bytes;
use tokio::net::TcpStream;
use tokio_rustls::TlsConnector as TokioTlsConnector;

use mamadvpn_common::ClientHelloBuilder;

use crate::tls::connector::build_client_config;
use crate::tls::{BoxedStream, FingerprintKind, TlsBufferIo, TlsConnector, TlsConnectorConfig};

/// TLS connector that places a custom `ClientHelloBuilder` fingerprint on
/// the wire before completing the handshake with rustls.
///
/// ## Usage
///
/// ```rust,ignore
/// let config = TlsConnectorConfig {
///     fingerprint: FingerprintKind::Chrome,
///     ..Default::default()
/// };
/// let connector = CustomClientHelloConnector::new(config)?;
/// let tls_stream = connector.connect("example.com", tcp_stream).await?;
/// ```
#[derive(Clone)]
pub struct CustomClientHelloConnector {
    /// The inner tokio-rustls connector (shares config with RustlsConnector).
    inner: TokioTlsConnector,
    /// The fingerprint config for ClientHelloBuilder.
    fingerprint: FingerprintKind,
    /// The SNI to embed in the custom ClientHello.
    custom_sni: Option<String>,
}

impl CustomClientHelloConnector {
    /// Create a new `CustomClientHelloConnector`.
    ///
    /// Builds a `rustls::ClientConfig` from the given config and wraps it in
    /// a `TokioTlsConnector` for TLS handshakes.
    pub fn new(config: TlsConnectorConfig) -> Result<Self> {
        let fingerprint = config.fingerprint;
        let custom_sni = None;

        // Build a full ClientConfig, then wrap in TokioTlsConnector
        let client_config = build_client_config(&config)?;
        let inner = TokioTlsConnector::from(Arc::new(client_config));

        Ok(Self {
            inner,
            fingerprint,
            custom_sni,
        })
    }

    /// Set a custom SNI to embed in the ClientHello.
    /// If not set, the `domain` argument from `connect()` is used.
    pub fn with_custom_sni(mut self, sni: String) -> Self {
        self.custom_sni = Some(sni);
        self
    }

    /// Generate a custom ClientHello bytes for the given SNI.
    fn build_custom_ch(&self, sni: &[u8]) -> Bytes {
        match self.fingerprint {
            FingerprintKind::Chrome | FingerprintKind::Random => {
                ClientHelloBuilder::generate(sni)
            }
            FingerprintKind::Firefox => {
                ClientHelloBuilder::generate(sni)
            }
            FingerprintKind::Android => {
                ClientHelloBuilder::generate(sni)
            }
        }
    }
}

#[async_trait::async_trait]
impl TlsConnector for CustomClientHelloConnector {
    /// Connect to `domain` over TLS, placing our custom ClientHello on the wire.
    ///
    /// 1. Generates a custom ClientHello using `ClientHelloBuilder` with the
    ///    configured fingerprint and SNI.
    /// 2. Wraps the TCP stream in a `TlsBufferIo` that sends our custom CH
    ///    on the first write (replacing rustls's own CH).
    /// 3. Uses `TokioTlsConnector` directly for the cryptographic handshake
    ///    (no delegation to `RustlsConnector`).
    async fn connect(&self, domain: &str, stream: TcpStream) -> Result<BoxedStream> {
        // Determine SNI: use custom_sni if set, otherwise use domain
        let sni = self
            .custom_sni
            .as_deref()
            .unwrap_or(domain)
            .as_bytes();

        // Step 1: Generate the custom ClientHello with our builder
        let custom_ch = self.build_custom_ch(sni);
        tracing::debug!(
            sni = %self.custom_sni.as_deref().unwrap_or(domain),
            fingerprint = ?self.fingerprint,
            ch_len = custom_ch.len(),
            "Sending custom ClientHello on the wire"
        );

        // Step 2: Wrap the TCP stream so the first write sends our CH
        let buffered_stream = TlsBufferIo::new(stream, custom_ch);

        // Step 3: Use TokioTlsConnector directly on the buffered stream.
        // The TlsBufferIo intercepts the first write (rustls's ClientHello)
        // and replaces it with our custom CH.
        let server_name = rustls::pki_types::ServerName::try_from(domain.to_string())
            .with_context(|| format!("Invalid SNI domain: {domain}"))?;

        let tls_stream = self
            .inner
            .connect(server_name, buffered_stream)
            .await
            .with_context(|| format!("CustomClientHello TLS handshake failed for {domain}"))?;

        Ok(Box::pin(tls_stream))
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_custom_connector_creation() {
        let config = TlsConnectorConfig {
            fingerprint: FingerprintKind::Chrome,
            verify_certs: false,
            ..Default::default()
        };
        let connector = CustomClientHelloConnector::new(config).unwrap();
        assert_eq!(connector.fingerprint, FingerprintKind::Chrome);
    }

    #[test]
    fn test_custom_connector_with_custom_sni() {
        let config = TlsConnectorConfig {
            fingerprint: FingerprintKind::Chrome,
            verify_certs: false,
            ..Default::default()
        };
        let connector = CustomClientHelloConnector::new(config)
            .unwrap()
            .with_custom_sni("www.cloudflare.com".into());
        assert_eq!(
            connector.custom_sni.as_deref(),
            Some("www.cloudflare.com")
        );
    }

    #[test]
    fn test_build_custom_ch_contains_sni() {
        let config = TlsConnectorConfig {
            fingerprint: FingerprintKind::Chrome,
            verify_certs: false,
            ..Default::default()
        };
        let connector = CustomClientHelloConnector::new(config).unwrap();
        let sni = b"www.cloudflare.com";
        let ch = connector.build_custom_ch(sni);
        assert!(
            ch.windows(sni.len()).any(|w| w == sni),
            "Custom ClientHello should contain the SNI"
        );
    }

    #[test]
    fn test_build_custom_ch_is_tls_handshake() {
        let config = TlsConnectorConfig {
            fingerprint: FingerprintKind::Chrome,
            verify_certs: false,
            ..Default::default()
        };
        let connector = CustomClientHelloConnector::new(config).unwrap();
        let ch = connector.build_custom_ch(b"example.com");
        assert_eq!(ch[0], 0x16, "First byte must be TLS Handshake (0x16)");
    }

    #[test]
    fn test_tls_buffer_io_first_write_replaced() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};

        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();

        rt.block_on(async {
            let (mut a, mut b) = tokio::io::duplex(4096);

            let custom_data = Bytes::from_static(b"CUSTOM_CLIENT_HELLO");
            let mut buffered = TlsBufferIo::new(&mut a, custom_data.clone());

            buffered.write_all(b"RUSTLS_CH").await.unwrap();
            buffered.flush().await.unwrap();

            let mut buf = vec![0u8; 20];
            let n = b.read(&mut buf).await.unwrap();
            assert_eq!(&buf[..n], b"CUSTOM_CLIENT_HELLO");
        });
    }

    #[test]
    fn test_tls_buffer_io_second_write_passthrough() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};

        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();

        rt.block_on(async {
            let (mut a, mut b) = tokio::io::duplex(4096);

            let custom_data = Bytes::from_static(b"CUSTOM_CH");
            let mut buffered = TlsBufferIo::new(&mut a, custom_data.clone());

            buffered.write_all(b"IGNORED").await.unwrap();
            buffered.flush().await.unwrap();

            let mut buf = vec![0u8; 20];
            let n = b.read(&mut buf).await.unwrap();
            assert_eq!(&buf[..n], b"CUSTOM_CH");

            buffered.write_all(b"PASSTHROUGH").await.unwrap();
            buffered.flush().await.unwrap();

            let n = b.read(&mut buf).await.unwrap();
            assert_eq!(&buf[..n], b"PASSTHROUGH");
        });
    }
}
